package com.example.demo.di

import com.example.demo.data.remote.CarQueryApi
import com.example.demo.data.repository.CarRepositoryImpl
import com.example.demo.domain.repository.CarRepository
import com.example.demo.domain.usecase.GetCarsUseCase
import dagger.Module
import dagger.Provides
import dagger.hilt.InstallIn
import dagger.hilt.components.SingletonComponent
import okhttp3.OkHttpClient
import retrofit2.Retrofit
import retrofit2.converter.gson.GsonConverterFactory
import javax.inject.Singleton

/**
 * Dagger Hilt module that provides application-level dependencies.
 *
 * This object defines how to create instances of the network clients, repositories,
 * and use cases. These dependencies live for the entire lifecycle of the application
 * (Singleton scope) because the module is installed in [SingletonComponent].
 *
 * @author JOUBITI MOHAMMED
 */
@Module
@InstallIn(SingletonComponent::class)
object AppModule {

    /**
     * The base URL for the Car Query API.
     */
    private const val BASE_URL = "https://www.carqueryapi.com/api/0.3/"

    /**
     * Provides a singleton instance of [OkHttpClient].
     *
     * This client handles the underlying HTTP connections and can be configured
     * with interceptors (e.g., for logging or headers) if needed in the future.
     *
     * @return A built OkHttpClient instance.
     */
    @Provides
    @Singleton
    fun provideOkHttpClient(): OkHttpClient = OkHttpClient.Builder().build()

    /**
     * Provides a singleton instance of [Retrofit].
     *
     * Retrofit is configured with the [BASE_URL] and the [GsonConverterFactory]
     * to automatically parse JSON responses into Kotlin data classes.
     *
     * @param client The [OkHttpClient] to be used for network requests.
     * @return A configured Retrofit instance.
     */
    @Provides
    @Singleton
    fun provideRetrofit(client: OkHttpClient): Retrofit =
        Retrofit.Builder()
            .baseUrl(BASE_URL)
            .client(client)
            .addConverterFactory(GsonConverterFactory.create())
            .build()

    /**
     * Provides the [CarQueryApi] service interface.
     *
     * This is the actual implementation of the API endpoints generated by Retrofit.
     *
     * @param retrofit The configured Retrofit instance.
     * @return An implementation of [CarQueryApi].
     */
    @Provides
    @Singleton
    fun provideCarQueryApi(retrofit: Retrofit): CarQueryApi =
        retrofit.create(CarQueryApi::class.java)

    /**
     * Provides the [CarRepository] implementation.
     *
     * This binds the interface [CarRepository] to its concrete implementation [CarRepositoryImpl].
     * This allows the domain layer to depend on the abstraction rather than the concrete class.
     *
     * @param api The remote API service needed by the repository.
     * @return An instance of [CarRepositoryImpl] cast as [CarRepository].
     */
    @Provides
    @Singleton
    fun provideCarRepository(api: CarQueryApi): CarRepository =
        CarRepositoryImpl(api)

    /**
     * Provides the [GetCarsUseCase].
     *
     * Use cases encapsulate specific business logic. This use case is responsible
     * for retrieving the list of cars.
     *
     * @param repository The repository required to fetch data.
     * @return An instance of [GetCarsUseCase].
     */
    @Provides
    @Singleton
    fun provideGetCarsUseCase(repository: CarRepository): GetCarsUseCase =
        GetCarsUseCase(repository)
}